### ISSUE TITLE
Stacktrace in output: NoSuchMethodException: org.openrewrite.config.Environment$CompositeRecipe.getVisitor()

### ISSUE THREAD

**Issue by murdos** [openrewrite/rewrite-maven-plugin#186]
Not blocking, but it adds noise to outpout.
Related to #185
```
[INFO] Validating active recipes...
[INFO] Parsing Java files...
java.lang.NoSuchMethodException: org.openrewrite.config.Environment$CompositeRecipe.getVisitor()
	at java.base/java.lang.Class.getDeclaredMethod(Class.java:2475)
	at org.openrewrite.maven.AbstractRewriteMojo.discoverRecipeTypes(AbstractRewriteMojo.java:342)
	at org.openrewrite.maven.AbstractRewriteMojo.listResults(AbstractRewriteMojo.java:274)
	at org.openrewrite.maven.RewriteRunMojo.execute(RewriteRunMojo.java:39)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:957)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:193)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:47)
[INFO] Skipping YAML files because there are no active YAML recipes.
[INFO] Skipping properties files because there are no active properties recipes.
[INFO] Skipping XML files because there are no active XML recipes.
[INFO] Skipping Maven POM files because there are no active Maven recipes.
```

**Comment by jkschneider** [comment]
Thanks for pointing this out.
