### ISSUE TITLE
Test fails

### ISSUE THREAD

**Issue by Guseyn** [openrewrite/rewrite-maven-plugin#55]
When I run the test, I get error:
```
junit.framework.AssertionFailedError: The MojoDescriptor for the goal warn cannot be null.

	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.assertTrue(Assert.java:22)
	at junit.framework.Assert.assertNotNull(Assert.java:256)
	at junit.framework.TestCase.assertNotNull(TestCase.java:399)
	at org.apache.maven.plugin.testing.AbstractMojoTestCase.newMojoExecution(AbstractMojoTestCase.java:515)
	at org.openrewrite.maven.RewriteWarnMojoTest.setUp(RewriteWarnMojoTest.java:93)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
.....
```

**Comment by sambsnyd** [comment]
Is this running `mvn test`?
What version of maven are you using? 
What version of the JDK are you using?

Build & tests pass for me.
```
❯ mvn --version
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /home/sam/.m2/wrapper/dists/apache-maven-3.6.3-bin/1iopthnavndlasol9gbrbg6bf2/apache-maven-3.6.3
Java version: 1.8.0_265, vendor: Private Build, runtime: /usr/lib/jvm/java-8-openjdk-amd64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.4.0-19041-microsoft", arch: "amd64", family: "unix"
```

**Comment by Guseyn** [comment]
@sambsnyd sorry, I was just running tests via intelijidea, when I run with maven - it works, thanks
