### ISSUE TITLE
Duplicate key org.openrewrite.config.DeclarativeRecipe

### ISSUE THREAD

**Issue by glebt-aft** [openrewrite/rewrite-maven-plugin#867]
## What version of OpenRewrite are you using?
I am using

- rewrite-plugin
- - org.openrewrite.maven: 5.40.2
- - org.openrewrite.gradle: 8.35.4
- Maven/Gradle
- - Maven: 3.9.9
- - Gradle: 7.6.4

## How are you running OpenRewrite?
I am using the InteliJ built in plugin for OpenRewrite and I'm trying to execute the `org.openrewrite.java.migrate.Java8toJava11`

## What is the smallest, simplest way to reproduce the problem?
Download the recipe https://github.com/openrewrite/rewrite-migrate-java/blob/83287c50bf09827ceb5a7786266c4f3e9e50836b/src/main/resources/META-INF/rewrite/java-version-11.yml#L18

Open new project in InteliJ with Java 1.8 (Gradle/Maven) and run it

## What did you see instead?
For Gradle project:
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':rewriteRun'.
> java.lang.IllegalStateException: Duplicate key org.openrewrite.config.DeclarativeRecipe@68f8e059
```

For Maven project:
```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.349 s
[INFO] Finished at: 2024-09-23T12:57:29+03:00
[INFO] Final Memory: 52M/1815M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.openrewrite.maven:rewrite-maven-plugin:5.40.2:run (default-cli) on project something: Execution default-cli of goal org.openrewrite.maven:rewrite-maven-plugin:5.40.2:run failed: Duplicate key org.openrewrite.config.DeclarativeRecipe@68f8e059 -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
```

I have tried to run this on multiple projects (Maven and Gradle), and it didn't work. When I tried to run spring-boot migration it did worked for some reason.

**Comment by timtebeek** [comment]
hi @glebt-aft ; There's no need to copy that `java-version-11.yml` file; You can run the recipe without copying that file with this command:
```shell
mvn -U org.openrewrite.maven:rewrite-maven-plugin:run -Drewrite.recipeArtifactCoordinates=org.openrewrite.recipe:rewrite-migrate-java:RELEASE -Drewrite.activeRecipes=org.openrewrite.java.migrate.Java8toJava11 -Drewrite.exportDatatables=true
```
As seen here: https://docs.openrewrite.org/recipes/java/migrate/java8tojava11

What gave you the impression that you had to download that file? Wondering if it's something in our docs, or an external blog.

If you want to customize the recipe then you should also give it another name; That would prevent the `Duplicate key` error you're seeing.

**Comment by glebt-aft** [comment]
Hey @timtebeek, first of all, thank you very much for the quick reply! IntelliJ has support for Openwrite files, so I assumed I could just copy it and run it from the IDE (picture attached)
![image](https://github.com/user-attachments/assets/852a0092-aa26-4b6a-8679-774edd08cb7e)

Regarding your solution, I ran the Maven migration, and it looks like it worked!

Now, with the Gradle project, I'm getting some NullpointerException:

```
Execution failed for task ':rewriteRun'.
> java.lang.RuntimeException: Error while visiting build.gradle: java.lang.NullPointerException: null
    java.util.Objects.requireNonNull(Objects.java:203)
    org.openrewrite.gradle.UpgradeDependencyVersion$1.visitMethodInvocation(UpgradeDependencyVersion.java:230)
    org.openrewrite.gradle.UpgradeDependencyVersion$1.visitMethodInvocation(UpgradeDependencyVersion.java:149)
    org.openrewrite.java.tree.J$MethodInvocation.acceptJava(J.java:3905)
    org.openrewrite.java.tree.J.accept(J.java:59)
    org.openrewrite.TreeVisitor.visit(TreeVisitor.java:245)
    org.openrewrite.TreeVisitor.visitAndCast(TreeVisitor.java:317)
    org.openrewrite.java.JavaVisitor.visitRightPadded(JavaVisitor.java:1365)
    org.openrewrite.java.JavaVisitor.lambda$visitBlock$4(JavaVisitor.java:397)
    org.openrewrite.internal.ListUtils.map(ListUtils.java:176)
    org.openrewrite.java.JavaVisitor.visitBlock(JavaVisitor.java:396)
    org.openrewrite.java.tree.J$Block.acceptJava(J.java:838)
    org.openrewrite.java.tree.J.accept(J.java:59)
    org.openrewrite.TreeVisitor.visit(TreeVisitor.java:245)
    org.openrewrite.TreeVisitor.visitAndCast(TreeVisitor.java:317)
    org.openrewrite.java.JavaVisitor.visitLambda(JavaVisitor.java:797)
    ...

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':rewriteRun'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:207)
	at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:263)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:205)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:186)
	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:114)
	at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:62)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
	at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:41)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:370)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:357)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:350)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:336)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.lambda$run$0(DefaultPlanExecutor.java:127)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:191)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:182)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:124)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: Error while visiting build.gradle: java.lang.NullPointerException: null
  java.util.Objects.requireNonNull(Objects.java:203)
  org.openrewrite.gradle.UpgradeDependencyVersion$1.visitMethodInvocation(UpgradeDependencyVersion.java:230)
  org.openrewrite.gradle.UpgradeDependencyVersion$1.visitMethodInvocation(UpgradeDependencyVersion.java:149)
  org.openrewrite.java.tree.J$MethodInvocation.acceptJava(J.java:3905)
  org.openrewrite.java.tree.J.accept(J.java:59)
  org.openrewrite.TreeVisitor.visit(TreeVisitor.java:245)
  org.openrewrite.TreeVisitor.visitAndCast(TreeVisitor.java:317)
  org.openrewrite.java.JavaVisitor.visitRightPadded(JavaVisitor.java:1365)
  org.openrewrite.java.JavaVisitor.lambda$visitBlock$4(JavaVisitor.java:397)
  org.openrewrite.internal.ListUtils.map(ListUtils.java:176)
  org.openrewrite.java.JavaVisitor.visitBlock(JavaVisitor.java:396)
  org.openrewrite.java.tree.J$Block.acceptJava(J.java:838)
  org.openrewrite.java.tree.J.accept(J.java:59)
  org.openrewrite.TreeVisitor.visit(TreeVisitor.java:245)
  org.openrewrite.TreeVisitor.visitAndCast(TreeVisitor.java:317)
  org.openrewrite.java.JavaVisitor.visitLambda(JavaVisitor.java:797)
  ...
	at org.openrewrite.gradle.DelegatingProjectParser.unwrapInvocationException(DelegatingProjectParser.java:172)
	at org.openrewrite.gradle.DelegatingProjectParser.run(DelegatingProjectParser.java:114)
	at org.openrewrite.gradle.RewriteRunTask.run(RewriteRunTask.java:36)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:104)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:49)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:42)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:28)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:722)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:689)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$3.run(ExecuteActionsTaskExecuter.java:569)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:402)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:394)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:92)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:554)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:537)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.access$300(ExecuteActionsTaskExecuter.java:108)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution.executeWithPreviousOutputFiles(ExecuteActionsTaskExecuter.java:278)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution.execute(ExecuteActionsTaskExecuter.java:267)
	at org.gradle.internal.execution.steps.ExecuteStep.lambda$execute$1(ExecuteStep.java:33)
	at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:33)
	at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:26)
	at org.gradle.internal.execution.steps.CleanupOutputsStep.execute(CleanupOutputsStep.java:67)
	at org.gradle.internal.execution.steps.CleanupOutputsStep.execute(CleanupOutputsStep.java:36)
	at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:49)
	at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:34)
	at org.gradle.internal.execution.steps.CancelExecutionStep.execute(CancelExecutionStep.java:43)
	at org.gradle.internal.execution.steps.TimeoutStep.executeWithoutTimeout(TimeoutStep.java:73)
	at org.gradle.internal.execution.steps.TimeoutStep.execute(TimeoutStep.java:54)
	at org.gradle.internal.execution.steps.CatchExceptionStep.execute(CatchExceptionStep.java:34)
	at org.gradle.internal.execution.steps.CreateOutputsStep.execute(CreateOutputsStep.java:44)
	at org.gradle.internal.execution.steps.SnapshotOutputsStep.execute(SnapshotOutputsStep.java:54)
	at org.gradle.internal.execution.steps.SnapshotOutputsStep.execute(SnapshotOutputsStep.java:38)
	at org.gradle.internal.execution.steps.BroadcastChangingOutputsStep.execute(BroadcastChangingOutputsStep.java:49)
	at org.gradle.internal.execution.steps.CacheStep.executeWithoutCache(CacheStep.java:159)
	at org.gradle.internal.execution.steps.CacheStep.execute(CacheStep.java:72)
	at org.gradle.internal.execution.steps.CacheStep.execute(CacheStep.java:43)
	at org.gradle.internal.execution.steps.StoreExecutionStateStep.execute(StoreExecutionStateStep.java:44)
	at org.gradle.internal.execution.steps.StoreExecutionStateStep.execute(StoreExecutionStateStep.java:33)
	at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:38)
	at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:24)
	at org.gradle.internal.execution.steps.SkipUpToDateStep.executeBecause(SkipUpToDateStep.java:92)
	at org.gradle.internal.execution.steps.SkipUpToDateStep.lambda$execute$0(SkipUpToDateStep.java:85)
	at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:55)
	at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:39)
	at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:76)
	at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:37)
	at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:36)
	at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:26)
	at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:94)
	at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:49)
	at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:79)
	at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:53)
	at org.gradle.internal.execution.steps.ValidateStep.execute(ValidateStep.java:74)
	at org.gradle.internal.execution.steps.SkipEmptyWorkStep.lambda$execute$2(SkipEmptyWorkStep.java:78)
	at org.gradle.internal.execution.steps.SkipEmptyWorkStep.execute(SkipEmptyWorkStep.java:78)
	at org.gradle.internal.execution.steps.SkipEmptyWorkStep.execute(SkipEmptyWorkStep.java:34)
	at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsStartedStep.execute(MarkSnapshottingInputsStartedStep.java:39)
	at org.gradle.internal.execution.steps.LoadExecutionStateStep.execute(LoadExecutionStateStep.java:40)
	at org.gradle.internal.execution.steps.LoadExecutionStateStep.execute(LoadExecutionStateStep.java:28)
	at org.gradle.internal.execution.impl.DefaultWorkExecutor.execute(DefaultWorkExecutor.java:33)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:194)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:186)
	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:114)
	at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:62)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
	at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:41)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:370)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:357)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:350)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:336)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.lambda$run$0(DefaultPlanExecutor.java:127)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:191)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:182)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:124)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
Caused by: java.lang.RuntimeException: Error while visiting build.gradle: java.lang.NullPointerException: null
  java.util.Objects.requireNonNull(Objects.java:203)
  org.openrewrite.gradle.UpgradeDependencyVersion$1.visitMethodInvocation(UpgradeDependencyVersion.java:230)
  org.openrewrite.gradle.UpgradeDependencyVersion$1.visitMethodInvocation(UpgradeDependencyVersion.java:149)
  org.openrewrite.java.tree.J$MethodInvocation.acceptJava(J.java:3905)
  org.openrewrite.java.tree.J.accept(J.java:59)
  org.openrewrite.TreeVisitor.visit(TreeVisitor.java:245)
  org.openrewrite.TreeVisitor.visitAndCast(TreeVisitor.java:317)
  org.openrewrite.java.JavaVisitor.visitRightPadded(JavaVisitor.java:1365)
  org.openrewrite.java.JavaVisitor.lambda$visitBlock$4(JavaVisitor.java:397)
  org.openrewrite.internal.ListUtils.map(ListUtils.java:176)
  org.openrewrite.java.JavaVisitor.visitBlock(JavaVisitor.java:396)
  org.openrewrite.java.tree.J$Block.acceptJava(J.java:838)
  org.openrewrite.java.tree.J.accept(J.java:59)
  org.openrewrite.TreeVisitor.visit(TreeVisitor.java:245)
  org.openrewrite.TreeVisitor.visitAndCast(TreeVisitor.java:317)
  org.openrewrite.java.JavaVisitor.visitLambda(JavaVisitor.java:797)
  ...
	at org.openrewrite.gradle.isolated.ResultsContainer$1.lambda$preVisit$0(ResultsContainer.java:114)
	at org.openrewrite.gradle.isolated.ResultsContainer$1.preVisit(ResultsContainer.java:111)
	at org.openrewrite.gradle.isolated.ResultsContainer$1.preVisit(ResultsContainer.java:107)
	at org.openrewrite.gradle.isolated.ResultsContainer_1_GroovyVisitor.preVisit(ResultsContainer_1_GroovyVisitor.zig:102)
	at org.openrewrite.TreeVisitor.visit(TreeVisitor.java:242)
	at org.openrewrite.TreeVisitor.visitAndCast(TreeVisitor.java:317)
	at org.openrewrite.java.JavaVisitor.visitRightPadded(JavaVisitor.java:1365)
	at org.openrewrite.java.JavaVisitor.lambda$visitBlock$4(JavaVisitor.java:397)
	at org.openrewrite.internal.ListUtils.map(ListUtils.java:176)
	at org.openrewrite.java.JavaVisitor.visitBlock(JavaVisitor.java:396)
	at org.openrewrite.java.tree.J$Block.acceptJava(J.java:838)
	at org.openrewrite.java.tree.J.accept(J.java:59)
	at org.openrewrite.TreeVisitor.visit(TreeVisitor.java:245)
	at org.openrewrite.TreeVisitor.visitAndCast(TreeVisitor.java:317)
	at org.openrewrite.java.JavaVisitor.visitLambda(JavaVisitor.java:797)
	at org.openrewrite.java.tree.J$Lambda.acceptJava(J.java:3173)
	at org.openrewrite.java.tree.J.accept(J.java:59)
	at org.openrewrite.TreeVisitor.visit(TreeVisitor.java:245)
	at org.openrewrite.TreeVisitor.visitAndCast(TreeVisitor.java:317)
	at org.openrewrite.java.JavaVisitor.visitRightPadded(JavaVisitor.java:1365)
	at org.openrewrite.java.JavaVisitor.lambda$visitContainer$37(JavaVisitor.java:1415)
	at org.openrewrite.internal.ListUtils.map(ListUtils.java:176)
	at org.openrewrite.java.JavaVisitor.visitContainer(JavaVisitor.java:1415)
	at org.openrewrite.java.JavaVisitor.visitMethodInvocation(JavaVisitor.java:918)
	at org.openrewrite.java.tree.J$MethodInvocation.acceptJava(J.java:3905)
	at org.openrewrite.java.tree.J.accept(J.java:59)
	at org.openrewrite.TreeVisitor.visit(TreeVisitor.java:245)
	at org.openrewrite.TreeVisitor.visitAndCast(TreeVisitor.java:317)
	at org.openrewrite.groovy.GroovyVisitor.lambda$visitCompilationUnit$0(GroovyVisitor.java:44)
	at org.openrewrite.internal.ListUtils.map(ListUtils.java:176)
	at org.openrewrite.groovy.GroovyVisitor.visitCompilationUnit(GroovyVisitor.java:44)
	at org.openrewrite.groovy.tree.G$CompilationUnit.acceptGroovy(G.java:212)
	at org.openrewrite.groovy.tree.G.accept(G.java:47)
	at org.openrewrite.TreeVisitor.visit(TreeVisitor.java:245)
	at org.openrewrite.gradle.isolated.ResultsContainer.getRecipeErrors(ResultsContainer.java:118)
	at org.openrewrite.gradle.isolated.ResultsContainer.getFirstException(ResultsContainer.java:98)
	at org.openrewrite.gradle.isolated.DefaultProjectParser.run(DefaultProjectParser.java:426)
	at org.openrewrite.gradle.isolated.DefaultProjectParser.run(DefaultProjectParser.java:419)
	at org.openrewrite.gradle.DelegatingProjectParser.lambda$run$2(DelegatingProjectParser.java:115)
	at org.openrewrite.gradle.DelegatingProjectParser.unwrapInvocationException(DelegatingProjectParser.java:164)
	... 94 more
```


I have added to the `build.gradle` the following configurations as mentioned in the documentation:
```
import org.apache.tools.ant.taskdefs.condition.Os

buildscript {
    repositories {
        mavenCentral()
        ...
    }
    ...
}

plugins {
    ...
    id("org.openrewrite.rewrite") version("6.23.3")
}
...
sourceCompatibility = 1.8

repositories {
    mavenCentral()
}
...

dependencies{
    ...
    rewrite("org.openrewrite.recipe:rewrite-migrate-java:2.24.0")
}
...
rewrite {
    activeRecipe("org.openrewrite.java.migrate.Java8toJava11")
    exportDatatables = true
}
```

Not sure why it isn't working.

**Comment by timtebeek** [comment]
Thanks for the quick update! the NPE you're seeing was likely fixed five days ago: https://github.com/openrewrite/rewrite/commit/6d61f751cb6d2305ef439d36f97d7f8f5b28f1c0
It should land in the new rewrite-gradle-plugin release we do this Wednesday; hope that helps!
