### ISSUE TITLE
CycloneDX bom can't be imported into dependency track

### ISSUE THREAD

**Issue by sambsnyd** [openrewrite/rewrite-maven-plugin#94]
Here's the pom of the project we were trying this on: https://gist.github.com/Marx314/3748aadd16087f26bbd2c4bf6591613e

Here's a cyclonedx bom produced by our plugin: https://gist.github.com/Marx314/c1a8492532d931d5f224bdc9552393ed#file-annuaire-service-maven-1-0-0-0-cyclonedx-xml

Here's a cyclonedx bom produced by the cyclonedx plugin: https://gist.github.com/Marx314/c1a8492532d931d5f224bdc9552393ed#file-bom-xml

When imported into [dependency track](https://dependencytrack.org/) our bom results in errors in dependency track's log and only a single entry appearing in the UI. This is probably related to there being a single <component> in our bom and one <component> entry per dependency in the cyclonedx generated bom. Tried on both dependency track 3.8.0 and 4.1.0 (latest).

This is the stacktrace from dependencytrack's logs:
```
INSERT INTO COMPONENT (CLASSIFIER,COPYRIGHT,CPE,DESCRIPTION,EXTENSION,FILENAME,"GROUP",INTERNAL,LAST_RISKSCORE,LICENSE,MD5,"NAME",PARENT_COMPONENT_ID,PURL,LICENSE_ID,SHA1,SHA_256,SHA3_256,SHA3_512,SHA_512,UUID,VERSION) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) [23502-200]
at org.h2.message.DbException.getJdbcSQLException(DbException.java:459)
at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
at org.h2.message.DbException.get(DbException.java:205)
at org.h2.message.DbException.get(DbException.java:181)
at org.h2.table.Column.validateConvertUpdateSequence(Column.java:374)
at org.h2.table.Table.validateConvertUpdateSequence(Table.java:845)
at org.h2.command.dml.Insert.insertRows(Insert.java:187)
at org.h2.command.dml.Insert.update(Insert.java:151)
at org.h2.command.CommandContainer.executeUpdateWithGeneratedKeys(CommandContainer.java:272)
at org.h2.command.CommandContainer.update(CommandContainer.java:191)
at org.h2.command.Command.executeUpdate(Command.java:251)
at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:191)
at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:152)
at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
at org.datanucleus.store.rdbms.ParamLoggingPreparedStatement.executeUpdate(ParamLoggingPreparedStatement.java:393)
at org.datanucleus.store.rdbms.SQLController.executeStatementUpdate(SQLController.java:427)
at org.datanucleus.store.rdbms.request.InsertRequest.execute(InsertRequest.java:414)
at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.insertObjectInTable(RDBMSPersistenceHandler.java:162)
at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.insertObject(RDBMSPersistenceHandler.java:138)
at org.datanucleus.state.StateManagerImpl.internalMakePersistent(StateManagerImpl.java:4569)
at org.datanucleus.state.StateManagerImpl.makePersistent(StateManagerImpl.java:4546)
at org.datanucleus.ExecutionContextImpl.persistObjectInternal(ExecutionContextImpl.java:2026)
at org.datanucleus.ExecutionContextImpl.persistObjectWork(ExecutionContextImpl.java:1869)
at org.datanucleus.ExecutionContextImpl.persistObject(ExecutionContextImpl.java:1724)
at org.datanucleus.api.jdo.JDOPersistenceManager.jdoMakePersistent(JDOPersistenceManager.java:712)
... 9 common frames omittedINSERT INTO COMPONENT (CLASSIFIER,COPYRIGHT,CPE,DESCRIPTION,EXTENSION,FILENAME,"GROUP",INTERNAL,LAST_RISKSCORE,LICENSE,MD5,"NAME",PARENT_COMPONENT_ID,PURL,LICENSE_ID,SHA1,SHA_256,SHA3_256,SHA3_512,SHA_512,UUID,VERSION) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) [23502-200]
at org.h2.message.DbException.getJdbcSQLException(DbException.java:459)
at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
at org.h2.message.DbException.get(DbException.java:205)
at org.h2.message.DbException.get(DbException.java:181)
at org.h2.table.Column.validateConvertUpdateSequence(Column.java:374)
at org.h2.table.Table.validateConvertUpdateSequence(Table.java:845)
at org.h2.command.dml.Insert.insertRows(Insert.java:187)
at org.h2.command.dml.Insert.update(Insert.java:151)
at org.h2.command.CommandContainer.executeUpdateWithGeneratedKeys(CommandContainer.java:272)
at org.h2.command.CommandContainer.update(CommandContainer.java:191)
at org.h2.command.Command.executeUpdate(Command.java:251)
at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:191)
at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:152)
at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
at org.datanucleus.store.rdbms.ParamLoggingPreparedStatement.executeUpdate(ParamLoggingPreparedStatement.java:393)
at org.datanucleus.store.rdbms.SQLController.executeStatementUpdate(SQLController.java:427)
at org.datanucleus.store.rdbms.request.InsertRequest.execute(InsertRequest.java:414)
at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.insertObjectInTable(RDBMSPersistenceHandler.java:162)
at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.insertObject(RDBMSPersistenceHandler.java:138)
at org.datanucleus.state.StateManagerImpl.internalMakePersistent(StateManagerImpl.java:4569)
at org.datanucleus.state.StateManagerImpl.makePersistent(StateManagerImpl.java:4546)
at org.datanucleus.ExecutionContextImpl.persistObjectInternal(ExecutionContextImpl.java:2026)
at org.datanucleus.ExecutionContextImpl.persistObjectWork(ExecutionContextImpl.java:1869)
at org.datanucleus.ExecutionContextImpl.persistObject(ExecutionContextImpl.java:1724)
at org.datanucleus.api.jdo.JDOPersistenceManager.jdoMakePersistent(JDOPersistenceManager.java:712)
... 9 common frames omitted
```

**Comment by okundzich** [comment]
Let's keep this issue for importing CycloneDX bom  into dependency track UI and track dependency resolution issues separately.

**Comment by tkvangorder** [comment]
The format outputted by rewrite now conforms so the CycloneDX 1.2 BOM formation (http://cyclonedx.org/schema/bom/1.2)
